name: Build and push Image

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:                                             # <<-- Add default working directory
      run:                                                # <<-- here to ensure deployment 
        working-directory: ./Humongous.Healthcare/
        
    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag humongous-healthcare-api:$GITHUB_RUN_ID
      
      # Log in to Docker with service principal credentials
    - name: login to ACR
      run: docker login daiworkshopacrkpan.azurecr.io --username cd3c2b26-cef0-4435-88bc-fb23a8b28672 --password $SP_PASSWORD
        
    - name: Tag the docker image
      run: docker tag humongous-healthcare-api:$GITHUB_RUN_ID daiworkshopacrkpan.azurecr.io/humongous-healthcare-api:$GITHUB_RUN_ID

    - name: Push the image
      run: docker push daiworkshopacrkpan.azurecr.io/humongous-healthcare-api:$GITHUB_RUN_ID
