name: Build and push Image

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:                                             # <<-- Add default working directory
      run:                                                # <<-- here to ensure deployment 
        working-directory: ./Humongous.Healthcare/
        
    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag humongous-healthcare-api:${{ GITHUB.RUN_ID }}
        
    - name: Tag the docker image
      run: docker tag humongous-healthcare-api:${{ GITHUB.RUN_ID }} daiworkshopacrkpan.azurecr.io/humongous-healthcare-api:${{ env.VERSION }}

    - name: Push the image
      run: docker push daiworkshopacrkpan.azurecr.io/humongous-healthcare-api:${{ GITHUB.RUN_ID }}
